In [2]:
import pandas as pd

### Creating training data

In [3]:
df = pd.read_csv("/Users/anurag/Desktop/Computer Science/Monash/2023/FIT3164 Data Science Project Semester 2/Electricity-Demand-Forecasting/Data/data_for_analysis/actuals_1.csv")
df2 = pd.read_csv("/Users/anurag/Desktop/Computer Science/Monash/2023/FIT3164 Data Science Project Semester 2/Electricity-Demand-Forecasting/Data/data_for_analysis/actuals_2.csv")

#Create Whole Dataset
df_train = pd.concat([df, df2], axis = 0)

df_train['Time'] = pd.to_datetime(df_train['Time'])
df_train

/var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T/ipykernel_87809/2568991393.py:7: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_train['Time'] = pd.to_datetime(df_train['Time'])

,Time,Load (kW),Pressure_kpa,Cloud Cover (%),Humidity (%),Temperature (C),Wind Direction (deg),Wind Speed (kmh)
0,2017-03-18 00:00:00,1.031472e+06,1012.48000,2.125,79.333333,16.764386,285.250,6.25375
1,2017-03-18 01:00:00,1.007206e+06,1011.61875,0.000,82.166667,15.729386,285.000,9.20500
2,2017-03-18 02:00:00,9.861084e+05,1010.72000,2.125,81.666667,15.816886,316.000,11.28375
3,2017-03-18 03:00:00,9.707610e+05,1011.37625,17.125,82.250000,15.919386,327.000,7.16875
4,2017-03-18 04:00:00,9.622584e+05,1011.50000,18.625,82.333333,15.769386,282.250,0.78000
...,...,...,...,...,...,...,...,...
1683,2021-01-15 19:00:00,1.141079e+06,1013.38750,38.375,68.333333,11.734386,306.875,6.63375
1684,2021-01-15 20:00:00,1.108896e+06,1013.97500,28.125,73.916667,9.056886,297.625,10.08750
1685,2021-01-15 21:00:00,1.078978e+06,1014.18750,21.125,75.833333,8.414386,334.000,8.18000
1686,2021-01-15 22:00:00,1.044495e+06,1014.12500,17.375,74.250000,8.041886,73.625,4.12250
1687,2021-01-15 23:00:00,1.010234e+06,1013.90000,13.250,77.250000,6.541886,37.625,2.87000

### Creating testing set

In [4]:
df_test = pd.read_csv("/Users/anurag/Desktop/Computer Science/Monash/2023/FIT3164 Data Science Project Semester 2/Electricity-Demand-Forecasting/Data/Forecast_Data/forecasts.csv")

df_test['Time'] = pd.to_datetime(df_test['Time'])
df_test

/var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T/ipykernel_87809/1214534075.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_test['Time'] = pd.to_datetime(df_test['Time'])

,Time,Cloud Cover (%),Pressure_kpa,Temperature (C),Wind Direction (deg),Wind Speed (kmh)
0,2017-03-18 00:00:00,3,1011,14,307,2
1,2017-03-18 01:00:00,4,1011,14,215,2
2,2017-03-18 02:00:00,4,1011,14,123,1
3,2017-03-18 03:00:00,4,1011,14,31,1
4,2017-03-18 04:00:00,4,1011,14,138,1
...,...,...,...,...,...,...
32155,2020-11-16 19:00:00,30,1014,18,301,13
32156,2020-11-16 20:00:00,30,1014,18,271,12
32157,2020-11-16 21:00:00,31,1015,18,242,11
32158,2020-11-16 22:00:00,33,1015,18,169,10
32159,2020-11-16 23:00:00,36,1015,18,95,9

### Creating Data Structure

In [60]:
## Code from two cells ago but the first for loop starts a 0 (same), ends same, and step of 24.
import pandas as pd

def combine_rows_with_different_attribute_names(df, df_test):
    combined_data_list = []

    #start at 0, stop 168 + 1 rows before end, jump by 24 hours / 1 day.
    for i in range(0, len(df_test) - (168 + 1), 24):
        combined_data = {}
        
        if i + 168 + 24 >= (len(df_test)):
            break
        
        for j in range(168):
            row = df.iloc[i + j]

            # Iterate over columns and update column names
            for col, val in row.items():
                combined_data[f"{col}_date{j+1}"] = val
        
        # Append the combined data dictionary to the list
        
        for j in range(48):
            # if i + j + 168 >= (len(df_test) - 1):
            #     break
            row = df_test.iloc[i + j + 168]
            
            for col, val in row.items():
                combined_data[f"{col}_test_date{j+1}"] = val
            
            
        combined_data_list.append(combined_data)

    # Convert the list of dictionaries into a DataFrame
    combined_df = pd.DataFrame(combined_data_list)

    return combined_df

# Example usage:
# Assuming you have a DataFrame named df_train
result = combine_rows_with_different_attribute_names(df_train, df_test)
result

,Time_date1,Load (kW)_date1,Pressure_kpa_date1,Cloud Cover (%)_date1,Humidity (%)_date1,Temperature (C) _date1,Wind Direction (deg)_date1,Wind Speed (kmh)_date1,Time_date2,Load (kW)_date2,...,Pressure_kpa_test_date47,Temperature (C) _test_date47,Wind Direction (deg)_test_date47,Wind Speed (kmh)_test_date47,Time_test_date48,Cloud Cover (%)_test_date48,Pressure_kpa_test_date48,Temperature (C) _test_date48,Wind Direction (deg)_test_date48,Wind Speed (kmh)_test_date48
0,2017-03-18,1.031472e+06,1012.48000,2.125,79.333333,16.764386,285.250,6.25375,2017-03-18 01:00:00,1.007206e+06,...,1009,16,109,6,2017-03-26 23:00:00,0,1009,16,215,7
1,2017-03-19,1.021744e+06,1011.63500,44.000,89.666667,15.504386,245.875,7.27375,2017-03-19 01:00:00,9.995859e+05,...,1009,16,184,8,2017-03-27 23:00:00,0,1009,16,179,7
2,2017-03-20,9.871900e+05,1011.59500,0.000,87.750000,14.639386,254.250,8.64750,2017-03-20 01:00:00,9.672041e+05,...,1010,14,178,9,2017-03-28 23:00:00,0,1009,14,179,8
3,2017-03-21,1.032739e+06,1012.17875,44.000,86.000000,15.766886,219.500,9.14000,2017-03-21 01:00:00,1.003462e+06,...,1009,16,212,2,2017-03-29 23:00:00,0,1009,14,227,2
4,2017-03-22,1.034121e+06,1012.59375,19.000,81.750000,16.471886,201.000,10.45000,2017-03-22 01:00:00,1.009531e+06,...,1010,16,190,8,2017-03-30 23:00:00,0,1010,14,190,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,2020-11-04,1.031376e+06,1009.61250,62.000,78.666667,16.496886,67.250,9.42500,2020-11-04 01:00:00,1.019207e+06,...,1013,16,182,17,2020-11-12 23:00:00,3,1013,16,112,16
1328,2020-11-05,1.036251e+06,1010.86250,58.125,79.166667,15.881886,49.750,7.21125,2020-11-05 01:00:00,1.016650e+06,...,1015,16,53,16,2020-11-13 23:00:00,12,1015,16,57,16
1329,2020-11-06,1.016825e+06,1011.00000,36.500,71.583333,14.849386,313.125,10.43125,2020-11-06 01:00:00,1.000703e+06,...,1013,18,82,12,2020-11-14 23:00:00,47,1013,16,96,14
1330,2020-11-07,1.017038e+06,1012.40000,15.500,77.833333,12.846886,21.625,4.24625,2020-11-07 01:00:00,1.002246e+06,...,1014,16,301,12,2020-11-15 23:00:00,22,1014,16,269,12
1331,2020-11-08,1.015758e+06,1012.51250,2.000,82.500000,10.774386,80.500,6.20625,2020-11-08 01:00:00,1.003882e+06,...,1015,18,169,10,2020-11-16 23:00:00,36,1015,18,95,9

In [70]:
#Testing Correct Format
print(result['Time_date1'].iloc[1331], result['Time_date168'].iloc[1331])
print(result['Time_test_date1'].iloc[1331], result['Time_test_date48'].iloc[1331])

2020-11-08 00:00:00 2020-11-14 23:00:00
2020-11-15 00:00:00 2020-11-16 23:00:00